apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api
  labels:
    app: flask-api
  namespace: flaskapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-api
  template:
    metadata:
      labels:
        app: flask-api
    spec:
      containers:
      - name: flask-api
        image: nwajienelson/gitops:${env.BUILD_ID}
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "100Mi"
            cpu: "200m"
          limits:
            memory: "300Mi"
            cpu: "500m"
      #   volumeMounts:
      #   - name: flask-api-storage
      #     mountPath: /data
      # imagePullSecrets:
      #   - name: acr-auth
      # volumes:
      # - name: flask-api-storage
      #   persistentVolumeClaim:
      #     claimName: flask-api-pvc

